### ISSUE TITLE
add range list feature

### ISSUE THREAD

**Issue by daveloper** [PeymanHR/ipset#1]
Feature Request:
As a system administrator I want to list all IP addresses in each range.

**Comment by peymanhr** [comment]
This feature is not implemented since it is possible using a one liner and it can be applied to any ip/prefix range from argument.
```
python3 -c 'import ipaddress,sys;print("\n".join([str(x) for x in ipaddress.ip_network(sys.argv[1]).hosts()]))' 192.168.1.0/29
```

How would you like this feature to be implemented?
